### ISSUE TITLE
XlibNoSHM.c: file does not exist

### ISSUE THREAD

**Issue by roman-mkh** [mviereck/dockerfile-x11docker-xserver#1]
Steps to reproduce the problem:
$ x11docker --build x11docker/xserver
...
Step 9/20 : COPY XlibNoSHM.c /XlibNoSHM.c
COPY failed: file not found in build context or excluded by .dockerignore: stat XlibNoSHM.c: file does not exist

This repository provides the requested file, but even if I clone this repository and start build in it, it does not help.
In order to continue build I copied XlibNoSHM.c from this repository to working directory /temp/x11docker-build-x11docker-xserver/.  

Expected behavior: 11docker --build x11docker/xserver should copy all necessary files and build without non obviously manual steps

**Comment by mviereck** [comment]
Thank you for the report!
The bug is fixed in latest x11docker master version.
x11docker accidently downloaded `XlibNoSHM.so` instead of `XlibNoSHM.c`.

**Comment by roman-mkh** [comment]
Thank you. I see the change: [3f3ffb0ffaf02e3e073fdf8366e12d61a47f6aa2](https://github.com/mviereck/x11docker/commit/3f3ffb0ffaf02e3e073fdf8366e12d61a47f6aa2)
